### ISSUE TITLE
파이어폭스 버전이 v48 이후일 경우 의류 태그 출력이 안됨

### ISSUE THREAD

**Issue by 10001if** [opencloset/opencloset#947]
@keedi 말씀드린 것 처럼 크롬 브라우저에서는 의류 정보화면에서 의류태그 출력이 가능하나, 파이어폭스에서는 의류 태그 화면이 나타나지 않는 문제가 있습니다. 확인 부탁드립니다.

**Comment by 10001if** [comment]
@keedi 크롬으로 출력하고 있어서 당장 급하게 해결하지 않아도 될 듯 합니다. 마일스톤을 뒤로 조정하겠습니다.

**Comment by keedi** [comment]
파이어버그 콘솔로 확인시 다음과 같은 오류가 발생합니다.

![2016-11-02 17-34-59](https://cloud.githubusercontent.com/assets/138451/19921819/ebbe4532-a122-11e6-8e04-535bd75cd3fc.png)

**Comment by keedi** [comment]
오류 내용은 다음과 같습니다.

```
RangeError: invalid array length - pdfmake.min.js (line 12, col 14067)
```

현재 사용하는 [pdfmake](https://github.com/bpampuch/pdfmake) 버전은 2015년 10월 13일 릴리즈 된 0.1.20으로 가장 최신입니다. 다만 저장소에는 이후 최신 커밋 내역이 있습니다.

**Comment by keedi** [comment]
Invalid Array Length 오류 관련 내용은 다음 링크를 참고합니다.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length

----

# RangeError: invalid array length

## Message

```
RangeError: invalid array length (Firefox)
RangeError: Invalid array length (Chrome)
RangeError: Invalid array buffer length (Chrome)
```


## Error type

[RangeError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError)


## What went wrong?

An invalid array length might appear in these situations:

- When creating an [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) or an [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) which has a length which is either negative or larger or equal to 232, or
- when setting the [Array.length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/length) property to a value which is either negative or larger or equal to 232.

Why are Array and ArrayBuffer length limited? The length property of an Array or an ArrayBuffer is represented with an unsigned 32-bit integer, that can only store values which are in the range from 0 to 232-1.

If you are creating an Array, using the constructor, you probably want to use the literal notation instead, as the first argument is interpreted as the length of the Array.

Otherwise, you might want to clamp the length before setting the length property, or using it as argument of the constructor.


## Examples

### Invalid cases

```javascript
new Array(Math.pow(2, 40))
new Array(-1)
new ArrayBuffer(Math.pow(2, 32))
new ArrayBuffer(-1)

let a = [];
a.length = a.length - 1;         // set -1 to the length property

let b = new Array(Math.pow(2, 32) - 1);
b.length = b.length + 1;         // set 2^32 to the length property
```

### Valid cases

```javascript
[ Math.pow(2, 40) ]                     // [ 1099511627776 ]
[ -1 ]                                  // [ -1 ]
new ArrayBuffer(Math.pow(2, 32) - 1)
new ArrayBuffer(0)

let a = [];
a.length = Math.max(0, a.length - 1);

let b = new Array(Math.pow(2, 32) - 1);
b.length = Math.min(0xffffffff, b.length + 1);   

// 0xffffffff is the hexadecimal notation for 2^32 - 1
// which can also be written as (-1 >>> 0)
```

## See also

- [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array)
- [Array.length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/length)
- [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer)

**Comment by keedi** [comment]
[#577 - Invalid offset/length when creating typed array - pdfmake.js (24651,9) on Edge Windows 10](https://github.com/bpampuch/pdfmake/issues/577) 이슈와 연관이 있어보입니다.

대충 요약하면 파이어폭스의 경우 v48 부터 투명 png 파일을 내장할 경우 상기 오류가 발생하는 것으로 보입니다. 사람들의 토론 내용을 바탕으로 정리한 것이므로 실제로는 다를 수 있습니다. 구현했던 당시에는 문제가 없었으나 이후에 문제가 생긴 것을 보면 파이어폭스 버전업과 연관은 확실히 있으며, 이슈를 살펴보면 비단 파이어폭스에만 연관된 문제가 아님을 알 수 있습니다. 우리 역시 배경이미지를 위해 투명 png 를 사용하고 있기 때문에 관련이 있다고 보여집니다.

**Comment by keedi** [comment]
원래 사이트와 저장소 주소는 다음과 같습니다.

- http://pdfmake.org/
- https://github.com/bpampuch/pdfmake

브라우저 업데이트 등에 따른 후속 업데이트 릴리스 등이 이루어지지 않고 있는데 관련해서 다른 사람들이 포크해서 별도의 사이트와 저장소를 만들기도 한 것 같습니다.

- http://pdfmake.github.io
- https://github.com/pdfmake/pdfmake

포크한 저장소를 기준으로 우선 시도해볼 예정입니다.

**Comment by keedi** [comment]
bower 패키지 검색으로 확인해보면 기존 `pdfmake`의 패키지 이름은 `pdfmake`이며 포크 후 새로 릴리스를 하고 있는 저장소의 패키지 이름은 `pdfmake-dist`임을 알 수 있습니다.

![screenshot-bower io 2016-11-02 17-57-08](https://cloud.githubusercontent.com/assets/138451/19922422/e2e2207a-a125-11e6-9bde-d802d65c6fff.png)

**Comment by keedi** [comment]
현재 [pdfmake/pdfmake](https://github.com/pdfmake/pdfmake)의 가장 최신 릴리스 버전은 v0.1.31 입니다.

**Comment by keedi** [comment]
테스트 삼아 간단하게 확인해보았는데 포크한 저장소의 최신 0.1.31 버전은 해당 문제가 해결된 것으로 보입니다. 금일 관련해서 적용하고 배포하겠습니다.

**Comment by keedi** [comment]
#958 이슈와도 제법 밀접하게 연관이 있으므로 우선 처리합니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

금일 저녁에 배포할 예정입니다.

**Comment by keedi** [comment]
배포 완료 되었습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
